swagger: '2.0'
info:
  title: Subak API
  version: 1.0.0
  description: |
    Provides Subak Music Service APIs.
  contact:
    name: Subak Studio
    url: 'http://github.com/yeoupooh/'
    email: subak.studio@gmail.com
host: 'localhost:8081'
schemes:
  - http
basePath: /api
consumes:
  - application/json
produces:
  - application/json
paths:
  /engins:
    get:
      description: Gets all of engines.
      responses:
        '200':
          description: Success.
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  description: Unique Id for the engine.
                  type: string
                name:
                  description: Name of the engine to be displayed.
                  type: string
                type:
                  description: Type of the engine. "search" or "chart"
                  type: string
                path:
                  description: |
                    Relative URL of the engine. It can includes ":"
                  type: string
  '/bobborst/year/billboard/top/year/{year}':
    get:
      description: Gets tracks from Bobborst
      parameters:
        - description: Specified year.
          name: year
          in: path
          type: string
          required: true
      responses:
        '200':
          description: Response.
          schema:
            $ref: '#/definitions/responseOfTracks'
  '/{site}/{type}/{category}/{period}/tracks':
    get:
      description: Gets tracks from Melon
      parameters:
        - description: Id of the the site.
          name: site
          in: path
          type: string
          required: true
        - description: Type of the site.
          name: type
          in: path
          type: string
          required: true
        - description: Categroy of the site.
          name: category
          in: path
          type: string
          required: true
        - description: Period of the chart.
          name: period
          in: path
          type: string
          required: true
      responses:
        '200':
          description: Response.
          schema:
            $ref: '#/definitions/responseOfTracks'
definitions:
  responseOfTracks:
    description: Reponse of tracks requests.
    type: object
    properties:
      found:
        description: Number of tracks.
        type: integer
      tracks:
        type: array
        items:
          type: object
          properties:
            id:
              description: Id of the track.
              type: string
            artist:
              description: Artist of the track.
              type: string
            track:
              description: Name of the track.
              type: string
            albumart:
              description: Album Art URL of the track.
              type: string
